### ISSUE TITLE
Altura da seçao home em 720px

### ISSUE THREAD

**Issue by BBranco97** [pet-ads/apae#100]
O que aconteceu: a Seção Home não aparece por inteiro na tela do celular por causa da barra que fica ativa (tela 1520 x 720)
O que era esperado: o padding top deveria ser um pouco menor para a seção caber considerando  a barra
Passos para reproduzir: apenas entrar no site 
![WhatsApp Image 2023-12-18 at 13 07 11](https://github.com/pet-ads/apae/assets/131369036/7de8c995-666c-4b60-9cbe-3b22856c47fc)

**Comment by Analiviamotta** [comment]
Muito obrigada. 
Problema corrigido.
