### ISSUE TITLE
Seção Equipe com largura 720px

### ISSUE THREAD

**Issue by BBranco97** [pet-ads/apae#99]
O que aconteceu: As seção Equipe não aparece quando clicamos no link do menu (tela com 1520 x 720) 
Oque era esperado: A ancora realmente vai para turmas em mobile mas o padding entre elas deveria estar menor para visualizar as duas
Passos para reproduzir: menu->equipe
![WhatsApp Image 2023-12-18 at 13 01 36](https://github.com/pet-ads/apae/assets/131369036/f12da656-a173-466c-8074-35d016c746ec)

**Comment by Analiviamotta** [comment]
Muito obrigada. 
Problema corrigido.
